# Generated by Django 3.1 on 2021-02-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.CharField(default=565564, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.CharField(default='rr', max_length=30),
            preserve_default=False,
        ),
    ]
